"""
send_report.py — Send YouTube analysis report email via Resend API with .pptx attachment

Usage:
    python tools/send_report.py \
        --pptx .tmp/youtube_trends_report.pptx \
        --analysis .tmp/analysis_results.json \
        --to "recipient@example.com"

Setup:
    1. Sign up at https://resend.com (free — 3,000 emails/month)
    2. Create API Key → add to .env: RESEND_API_KEY=re_xxxxxxxxxxxx
"""

import argparse
import base64
import json
import os
import sys
from datetime import datetime
from pathlib import Path

import requests
from dotenv import load_dotenv

load_dotenv()

RESEND_API_URL = "https://api.resend.com/emails"


def build_email_html(analysis):
    """Build a clean HTML email with key insights."""
    summary = analysis.get("summary", {})
    insights = analysis.get("insights", [])
    top_videos = analysis.get("top_videos", {}).get("by_views", [])[:3]
    trending_kw = analysis.get("trending_keywords", [])[:5]

    # Top videos section
    top_videos_html = ""
    for i, v in enumerate(top_videos, 1):
        views = f"{v['view_count']:,}" if v["view_count"] < 1_000_000 else f"{v['view_count'] / 1_000_000:.1f}M"
        top_videos_html += f"""
        <tr>
            <td style="padding: 8px 12px; border-bottom: 1px solid #eee; color: #333;">
                {i}. {v['title'][:60]}{'...' if len(v['title']) > 60 else ''}
            </td>
            <td style="padding: 8px 12px; border-bottom: 1px solid #eee; text-align: right; color: #E94560; font-weight: bold;">
                {views} views
            </td>
        </tr>"""

    kw_html = " · ".join(f"<strong>{k['keyword']}</strong>" for k in trending_kw) if trending_kw else "N/A"
    insights_html = "".join(f"<li style='margin-bottom: 8px; color: #333;'>{ins}</li>" for ins in insights[:5])
    date_str = summary.get("fetch_date", datetime.now().strftime("%Y-%m-%d"))

    return f"""
    <div style="max-width: 600px; margin: 0 auto; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;">
        <div style="background: #1A1A2E; padding: 30px; text-align: center; border-radius: 8px 8px 0 0;">
            <h1 style="color: #E94560; margin: 0; font-size: 24px;">YouTube AI Trends Report</h1>
            <p style="color: #ccc; margin: 8px 0 0; font-size: 14px;">{date_str}</p>
        </div>

        <div style="background: #F5F6FA; padding: 20px 30px;">
            <table style="width: 100%; text-align: center;">
                <tr>
                    <td style="padding: 10px;">
                        <div style="font-size: 28px; font-weight: bold; color: #1A1A2E;">{summary.get('total_videos', 0):,}</div>
                        <div style="font-size: 12px; color: #888; margin-top: 4px;">Videos Analyzed</div>
                    </td>
                    <td style="padding: 10px;">
                        <div style="font-size: 28px; font-weight: bold; color: #1A1A2E;">{summary.get('total_channels', 0):,}</div>
                        <div style="font-size: 12px; color: #888; margin-top: 4px;">Channels</div>
                    </td>
                    <td style="padding: 10px;">
                        <div style="font-size: 28px; font-weight: bold; color: #E94560;">{summary.get('avg_engagement_rate', 0)}%</div>
                        <div style="font-size: 12px; color: #888; margin-top: 4px;">Avg Engagement</div>
                    </td>
                </tr>
            </table>
        </div>

        <div style="padding: 30px; background: white;">
            <p style="color: #555; font-size: 14px; text-align: center; margin-bottom: 24px;">
                Full report attached as PowerPoint (.pptx)
            </p>

            <h2 style="color: #1A1A2E; font-size: 18px; margin-bottom: 12px;">Top Performing Videos</h2>
            <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
                {top_videos_html}
            </table>

            <h2 style="color: #1A1A2E; font-size: 18px; margin-bottom: 12px;">Trending Keywords</h2>
            <p style="color: #555; line-height: 1.8; margin-bottom: 24px;">{kw_html}</p>

            <h2 style="color: #1A1A2E; font-size: 18px; margin-bottom: 12px;">Key Insights</h2>
            <ul style="padding-left: 20px; line-height: 1.8;">
                {insights_html}
            </ul>
        </div>

        <div style="background: #1A1A2E; padding: 20px 30px; text-align: center; border-radius: 0 0 8px 8px;">
            <p style="color: #888; font-size: 12px; margin: 0;">
                Generated by YouTube Analysis Automation · {date_str}
            </p>
        </div>
    </div>
    """


def main():
    parser = argparse.ArgumentParser(description="Send YouTube analysis report via Resend")
    parser.add_argument("--pptx", required=True, help="Path to the PowerPoint report file")
    parser.add_argument("--analysis", required=True, help="Path to analysis results JSON")
    parser.add_argument("--to", required=True, help="Recipient email(s), comma-separated")
    parser.add_argument("--subject", default=None, help="Email subject (auto-generated if omitted)")
    parser.add_argument("--from-name", default="YouTube Analysis Bot", help="Sender name")
    parser.add_argument("--from-email", default=None, help="Sender email (default: resend sandbox)")
    args = parser.parse_args()

    api_key = os.getenv("RESEND_API_KEY", "").strip()
    if not api_key:
        print("ERROR: RESEND_API_KEY not set in .env\nGet one free at: https://resend.com", file=sys.stderr)
        sys.exit(1)

    pptx_path = Path(args.pptx)
    if not pptx_path.exists():
        print(f"ERROR: PowerPoint file not found: {args.pptx}", file=sys.stderr)
        sys.exit(1)

    analysis_path = Path(args.analysis)
    if not analysis_path.exists():
        print(f"ERROR: Analysis file not found: {args.analysis}", file=sys.stderr)
        sys.exit(1)

    analysis = json.loads(analysis_path.read_text(encoding="utf-8"))
    date_str = analysis.get("summary", {}).get("fetch_date", datetime.now().strftime("%Y-%m-%d"))

    html_content = build_email_html(analysis)
    subject = args.subject or f"YouTube AI Trends Report — {date_str}"

    # From address
    from_email = args.from_email
    if not from_email:
        configured = os.getenv("RESEND_FROM_EMAIL", "").strip().split("#")[0].strip()
        from_email = configured if configured and "@" in configured and "yourdomain" not in configured else "onboarding@resend.dev"
    from_address = f"{args.from_name} <{from_email}>"

    recipients = [r.strip() for r in args.to.split(",") if r.strip()]

    # Read and encode the .pptx attachment
    pptx_bytes = pptx_path.read_bytes()
    pptx_b64 = base64.b64encode(pptx_bytes).decode("utf-8")

    print(f"Sending report email")
    print(f"  From:    {from_address}")
    print(f"  To:      {', '.join(recipients)}")
    print(f"  Subject: {subject}")
    print(f"  Attachment: {pptx_path.name} ({len(pptx_bytes) / 1024:.0f} KB)")

    payload = {
        "from": from_address,
        "to": recipients,
        "subject": subject,
        "html": html_content,
        "attachments": [
            {
                "filename": f"youtube_ai_trends_{date_str}.pptx",
                "content": pptx_b64,
                "content_type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            }
        ],
    }

    response = requests.post(
        RESEND_API_URL,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json=payload,
        timeout=120,
    )

    if response.status_code in (200, 201):
        data = response.json()
        print(f"Email sent successfully! ID: {data.get('id', 'unknown')}")
    else:
        try:
            error = response.json()
        except Exception:
            error = response.text
        print(f"ERROR: Resend API returned {response.status_code}: {error}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
